#!/usr/bin/env bash
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP &
dunst &
wl-paste -t text --watch clipman store &
gammastep -l 19:72 &
~/.nix-profile/libexec/polkit-gnome-authentication-agent-1 &
foot -s &
thunar --daemon &
waybar &
swaybg -o \* -i ~/Pictures/Wallpapers/default -m fill
