#!/bin/sh
dbus-update-activation-environment --all &
swaybg -m fill -i ~/Pictures/Wallpapers/default &
waybar &
dunst &
wl-paste -t text --watch clipman store &
gammastep -l 19:72 &
~/.nix-profile/libexec/polkit-gnome-authentication-agent-1 &
rclone mount --daemon gdrive: ~/Storage/gdrive &
foot -s &
thunar --daemon &
