{ config, pkgs, ... }: {
  programs.firefox = {
    enable = true;
    package = pkgs.firefox-wayland;
    profiles.sarvesh = {
      extraConfig = ''
        ${builtins.readFile (builtins.fetchurl "https://raw.githubusercontent.com/arkenfox/user.js/master/user.js")}
        user_pref("browser.quitShortcut.disabled", true);
        user_pref("browser.startup.homepage", "moz-extension://b2adf1d5-17ec-4204-9a5a-e37dae27b81e/index.html");
        user_pref("browser.startup.page", 1);
        user_pref("browser.tabs.closeWindowWithLastTab", false);
        user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[\"jid1-zadieub7xozojw_jetpack-browser-action\",\"sponsorblocker_ajay_app-browser-action\",\"smart-referer_meh_paranoid_pk-browser-action\",\"skipredirect_sblask-browser-action\",\"_c2c003ee-bd69-42a2-b0e9-6f34222cb046_-browser-action\",\"canvasblocker_kkapsner_de-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"urlbar-container\",\"save-to-pocket-button\",\"downloads-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"jid1-zadieub7xozojw_jetpack-browser-action\",\"sponsorblocker_ajay_app-browser-action\",\"smart-referer_meh_paranoid_pk-browser-action\",\"_c2c003ee-bd69-42a2-b0e9-6f34222cb046_-browser-action\",\"skipredirect_sblask-browser-action\",\"canvasblocker_kkapsner_de-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"widget-overflow-fixed-list\"],\"currentVersion\":17,\"newElementCount\":3}");
        user_pref("extensions.pocket.enabled", false);
        user_pref("extensions.screenshots.disabled", true);
        user_pref("gfx.webrender.all", true);
        user_pref("keyword.enabled", true);
        user_pref("layers.acceleration.force-enabled", true);
        user_perf("media.ffmpeg.vaapi.enabled", true);
        user_pref("network.cookie.lifetimePolicy", 0);
        user_pref("privacy.resistFingerprinting.letterboxing", false);
        user_pref("properties.content.enabled", true);
        user_pref("reader.parse-on-load.enabled", false);
        user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
        user_pref("ui.key.menuAccessKey", 0);
        user_pref("ui.systemUsesDarkTheme", 1);
      '';
      userChrome = ''
        /* Credits: Cascade */
        :root{--window-colour:#0a0a0a;--secondary-colour:#2a2a2a;--inverted-colour:#b0b0b0;--uc-identity-color-blue:#7ed6df;--uc-identity-color-turquoise:#55e6c1;--uc-identity-color-green:#b8e994;--uc-identity-color-yellow:#f7d794;--uc-identity-color-orange:#f19066;--uc-identity-color-red:#fc5c65;--uc-identity-color-pink:#f78fb3;--uc-identity-color-purple:#786fa6;--urlbar-popup-url-color:var(--uc-identity-color-purple) !important;--uc-border-radius:4px;--uc-urlbar-width:clamp(200px,40vw,500px);--uc-active-tab-width:clamp(100px,20vw,300px);--uc-inactive-tab-width:clamp(50px,15vw,200px);--show-tab-close-button:none;--show-tab-close-button-hover:none;--container-tabs-indicator-margin:10px}#back-button,#forward-button{display:none !important}#star-button{display:none !important}#urlbar-zoom-button{display:none !important}#PanelUI-button{margin-top:-5px;margin-bottom:44px}#PanelUI-menu-button{padding:0 !important;max-height:1px;list-style-image:none !important}#PanelUI-menu-button .toolbarbutton-icon{width:1px !important}
        #PanelUI-menu-button .toolbarbutton-badge-stack{padding:0 !important}#reader-mode-button{display:none !important}#tracking-protection-icon-container{display:none !important}#identity-permission-box{display:none !important}.tab-secondary-label{display:none !important}#pageActionButton{display:none !important}#page-action-buttons{display:none !important}#urlbar-go-button{display:none !important}:root{--uc-theme-colour:var(--window-colour,var(--toolbar-bgcolor));--uc-hover-colour:var(--secondary-colour,rgba(0,0,0,.2));--uc-inverted-colour:var(--inverted-colour,var(--toolbar-color));--button-bgcolor:var(--uc-theme-colour) !important;--button-hover-bgcolor:var(--uc-hover-colour) !important;--button-active-bgcolor:var(--uc-hover-colour) !important;--toolbarbutton-border-radius:var(--uc-border-radius) !important;--tab-border-radius:var(--uc-border-radius) !important;--lwt-text-color:var(--uc-inverted-colour) !important;--lwt-tab-text:var(--uc-inverted-colour) !important;--arrowpanel-border-radius:var(--uc-border-radius) !important;--tab-block-margin:2px !important}
        window,#main-window,#toolbar-menubar,#TabsToolbar,#PersonalToolbar,#navigator-toolbox,#sidebar-box,#nav-bar{-moz-appearance:none !important;border:none !important;box-shadow:none !important;background:var(--uc-theme-colour) !important}#PersonalToolbar toolbarbutton:not(:hover),#bookmarks-toolbar-button:not(:hover){filter:grayscale(1) !important}.titlebar-buttonbox-container{display:none !important}.titlebar-spacer{display:none !important}#tabbrowser-tabs[haspinnedtabs]:not([positionpinnedtabs])>#tabbrowser-arrowscrollbox>.tabbrowser-tab[first-visible-unpinned-tab]{margin-inline-start:0 !important}.tabbrowser-tab>.tab-stack>.tab-background{box-shadow:none !important}.tabbrowser-tab>.tab-stack>.tab-background{background:var(--uc-theme-colour) !important}.tabbrowser-tab[selected]>.tab-stack>.tab-background{background:var(--uc-hover-colour) !important}#tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab:is([visuallyselected=true],[multiselected])>.tab-stack>.tab-background:-moz-lwtheme{background:var(--uc-hover-colour) !important}
        .tabbrowser-tab:not([pinned]) .tab-close-button{display:var(--show-tab-close-button) !important}.tabbrowser-tab:not([pinned]):hover .tab-close-button{display:var(--show-tab-close-button-hover) !important}.tabbrowser-tab[selected][fadein]:not([pinned]){max-width:var(--uc-active-tab-width) !important}.tabbrowser-tab[fadein]:not([selected]):not([pinned]){max-width:var(--uc-inactive-tab-width) !important}.tabbrowser-tab[usercontextid]>.tab-stack>.tab-background>.tab-context-line{margin:-1px var(--container-tabs-indicator-margin) 0 var(--container-tabs-indicator-margin) !important;border-radius:var(--tab-border-radius) !important}.tab-icon-image:not([pinned]){opacity:1 !important}.tab-icon-overlay:not([crashed]),.tab-icon-overlay[pinned][crashed][selected]{top:5px !important;z-index:1 !important;padding:1.5px !important;inset-inline-end:-8px !important;width:16px !important;height:16px !important;border-radius:10px !important}.tab-icon-overlay:not([sharing],[crashed]):is([soundplaying],[muted],[activemedia-blocked]){stroke:transparent !important;background:0 0 !important;opacity:1 !important;fill-opacity:.8 !important;color:currentColor !important;stroke:var(--uc-theme-colour) !important;background-color:var(--uc-theme-colour) !important}
        .tabbrowser-tab[selected] .tab-icon-overlay:not([sharing],[crashed]):is([soundplaying],[muted],[activemedia-blocked]){stroke:var(--uc-hover-colour) !important;background-color:var(--uc-hover-colour) !important}.tab-icon-overlay:not([pinned],[sharing],[crashed]):is([soundplaying],[muted],[activemedia-blocked]){margin-inline-end:9.5px !important}.tabbrowser-tab:not([image]) .tab-icon-overlay:not([pinned],[sharing],[crashed]){top:0 !important;padding:0 !important;margin-inline-end:5.5px !important;inset-inline-end:0 !important}.tab-icon-overlay:not([crashed])[soundplaying]:hover,.tab-icon-overlay:not([crashed])[muted]:hover,.tab-icon-overlay:not([crashed])[activemedia-blocked]:hover{color:currentColor !important;stroke:var(--uc-inverted-colour) !important;background-color:var(--uc-inverted-colour) !important;fill-opacity:.95 !important}.tabbrowser-tab[selected] .tab-icon-overlay:not([crashed])[soundplaying]:hover,.tabbrowser-tab[selected] .tab-icon-overlay:not([crashed])[muted]:hover,.tabbrowser-tab[selected] .tab-icon-overlay:not([crashed])[activemedia-blocked]:hover{color:currentColor !important;stroke:var(--uc-inverted-colour) !important;background-color:var(--uc-inverted-colour) !important;fill-opacity:.95 !important}
        #TabsToolbar .tab-icon-overlay:not([crashed])[soundplaying],#TabsToolbar .tab-icon-overlay:not([crashed])[muted],#TabsToolbar .tab-icon-overlay:not([crashed])[activemedia-blocked]{color:var(--uc-inverted-colour) !important}#TabsToolbar .tab-icon-overlay:not([crashed])[soundplaying]:hover,#TabsToolbar .tab-icon-overlay:not([crashed])[muted]:hover,#TabsToolbar .tab-icon-overlay:not([crashed])[activemedia-blocked]:hover{color:var(--uc-theme-colour) !important}#nav-bar{border:none !important;box-shadow:none !important;background:0 0 !important}#navigator-toolbox{border-bottom:none !important}#urlbar,#urlbar *{outline:none !important;box-shadow:none !important}#urlbar-background{border:var(--uc-hover-colour) !important}#urlbar[focused=true]>#urlbar-background,#urlbar:not([open])>#urlbar-background{background:0 0 !important}#urlbar[open]>#urlbar-background{background:var(--uc-theme-colour) !important}.urlbarView-row:hover>.urlbarView-row-inner,.urlbarView-row[selected]>.urlbarView-row-inner{background:var(--uc-hover-colour) !important}
        @media (min-width:1000px){#TabsToolbar{margin-left:var(--uc-urlbar-width) !important}#nav-bar{margin:calc((var(--urlbar-min-height)*-1) - 8px) calc(100vw - var(--uc-urlbar-width)) 0 0 !important}}.identity-color-blue{--identity-tab-color:var(--uc-identity-color-blue) !important;--identity-icon-color:var(--uc-identity-color-blue) !important}.identity-color-turquoise{--identity-tab-color:var(--uc-identity-color-turquoise) !important;--identity-icon-color:var(--uc-identity-color-turquoise) !important}.identity-color-green{--identity-tab-color:var(--uc-identity-color-green) !important;--identity-icon-color:var(--uc-identity-color-green) !important}.identity-color-yellow{--identity-tab-color:var(--uc-identity-color-yellow) !important;--identity-icon-color:var(--uc-identity-color-yellow) !important}.identity-color-orange{--identity-tab-color:var(--uc-identity-color-orange) !important;--identity-icon-color:var(--uc-identity-color-orange) !important}.identity-color-red{--identity-tab-color:var(--uc-identity-color-red) !important;--identity-icon-color:var(--uc-identity-color-red) !important}
        .identity-color-pink{--identity-tab-color:var(--uc-identity-color-pink) !important;--identity-icon-color:var(--uc-identity-color-pink) !important}.identity-color-purple{--identity-tab-color:var(--uc-identity-color-purple) !important;--identity-icon-color:var(--uc-identity-color-purple) !important}
      '';
    };
  };
}
